-- Page: Syarat & Ketentuan
INSERT INTO pages (id, title, slug, type, status, is_homepage, show_breadcrumb, breadcrumb_image, parent_id, menu_order, created_at, updated_at) VALUES ('9', 'Syarat & Ketentuan', 'syarat-ketentuan', 'static', 'published', '0', '1', NULL, NULL, '0', '2026-02-23 07:22:07', '2026-02-23 07:22:07');

-- Sections for Page: Syarat & Ketentuan
INSERT INTO page_sections (id, page_id, section_key, position, is_active, config, created_at, updated_at) VALUES ('37', '9', 'legal_section', '1', '1', '{\"title\":\"Syarat & Ketentuan Penggunaan\",\"subtitle\":\"Legal ACTiV\",\"last_updated\":\"23 February 2026\",\"contact_email\":\"sales@activ.co.id\",\"sections\":[{\"slug\":\"pengantar\",\"title\":\"Pengantar\",\"icon\":\"fa-regular fa-file-lines\",\"content\":\"Selamat datang di situs web PT Alfa Cipta Teknologi Virtual (ACTiV). Dengan mengakses atau menggunakan layanan kami, Anda setuju untuk terikat oleh Syarat dan Ketentuan ini.\"},{\"slug\":\"definisi\",\"title\":\"Definisi\",\"icon\":\"fa-regular fa-book\",\"content\":\"<ul><li><strong>ACTiV:<\\/strong> PT Alfa Cipta Teknologi Virtual sebagai penyedia layanan ICT.<\\/li><li><strong>Layanan:<\\/strong> Meliputi rental hardware, penjualan software, konsultasi IT, dan platform Accommerce.id.<\\/li><li><strong>Pengguna:<\\/strong> Individu atau korporasi yang menggunakan layanan ACTiV.<\\/li><\\/ul>\"},{\"slug\":\"layanan-ict\",\"title\":\"Layanan & Sewa Perangkat\",\"icon\":\"fa-regular fa-laptop-code\",\"content\":\"Layanan penyewaan perangkat keras mengikuti durasi kontrak yang disepakati. Pengguna bertanggung jawab penuh atas keamanan fisik perangkat selama masa sewa.\",\"callout\":\"Setiap kerusakan yang disebabkan oleh kelalaian penggunaan akan dikenakan biaya penggantian sesuai harga pasar yang berlaku.\"},{\"slug\":\"pembayaran\",\"title\":\"Transaksi & Pembayaran\",\"icon\":\"fa-regular fa-credit-card\",\"content\":\"Pembayaran dilakukan melalui saluran resmi yang ditunjuk ACTiV atau melalui platform Accommerce.id. Untuk proyek kustom, berlaku ketentuan DP 50% sebelum pengerjaan dimulai.\"},{\"slug\":\"hukum\",\"title\":\"Hukum yang Berlaku\",\"icon\":\"fa-regular fa-gavel\",\"content\":\"Syarat dan Ketentuan ini diatur oleh hukum Republik Indonesia. Perselisihan akan diselesaikan melalui musyawarah atau di Pengadilan Negeri Jakarta Selatan.\"}]}', '2026-02-23 07:51:02', '2026-02-23 07:51:02');

-- Page: Kebijakan Privasi
INSERT INTO pages (id, title, slug, type, status, is_homepage, show_breadcrumb, breadcrumb_image, parent_id, menu_order, created_at, updated_at) VALUES ('10', 'Kebijakan Privasi', 'kebijakan-privasi', 'static', 'published', '0', '1', NULL, NULL, '0', '2026-02-23 07:22:07', '2026-02-23 07:22:07');

-- Sections for Page: Kebijakan Privasi
INSERT INTO page_sections (id, page_id, section_key, position, is_active, config, created_at, updated_at) VALUES ('38', '10', 'legal_section', '1', '1', '{\"title\":\"Kebijakan Privasi\",\"subtitle\":\"Privasi Anda\",\"last_updated\":\"23 February 2026\",\"contact_email\":\"sales@activ.co.id\",\"sections\":[{\"slug\":\"informasi-dikumpulkan\",\"title\":\"Data yang Kami Kumpulkan\",\"icon\":\"fa-regular fa-database\",\"content\":\"Kami mengumpulkan data profil perusahaan dan kontak personal untuk keperluan administrasi layanan ICT dan verifikasi transaksi di Accommerce.id.\"},{\"slug\":\"penggunaan-data\",\"title\":\"Cara Kami Menggunakan Data\",\"icon\":\"fa-regular fa-shield-halved\",\"content\":\"Data Anda digunakan secara eksklusif untuk penyediaan layanan, pemrosesan pesanan, dan peningkatan kualitas solusi IT kami.\",\"callout\":\"ACTiV tidak pernah menjual data pelanggan kepada pihak ketiga mana pun.\"}]}', '2026-02-23 07:51:02', '2026-02-23 07:51:02');

-- Page: Kemitraan
INSERT INTO pages (id, title, slug, type, status, is_homepage, show_breadcrumb, breadcrumb_image, parent_id, menu_order, created_at, updated_at) VALUES ('11', 'Kemitraan', 'kemitraan', 'static', 'published', '0', '1', NULL, NULL, '0', '2026-02-23 07:22:07', '2026-02-23 07:22:07');

-- Sections for Page: Kemitraan
INSERT INTO page_sections (id, page_id, section_key, position, is_active, config, created_at, updated_at) VALUES ('39', '11', 'partnership_hero', '0', '1', '{\"id\":\"section-39\",\"className\":\"\",\"title\":\"Bangun Kemitraan Strategis Bersama ACTiV\",\"subtitle\":\"Kolaborasi Tanpa Batas\",\"button_text\":\"Ajukan Kemitraan\",\"button_url\":\"\",\"use_whatsapp\":true,\"button_url_rel\":\"noopener noreferrer\",\"description\":\"Bergabunglah dengan ekosistem teknologi terdepan untuk menghadirkan solusi ICT dan Edukasi yang inovatif bagi klien Anda.\"}', '2026-02-23 07:51:02', '2026-02-23 08:28:25');
INSERT INTO page_sections (id, page_id, section_key, position, is_active, config, created_at, updated_at) VALUES ('40', '11', 'partnership_details', '1', '1', '{\"id\":\"section-40\",\"className\":\"\",\"title\":\"Bagian dari Ekosistem Digital ACTiV\",\"subtitle\":\"\\ud83c\\udf10 Official Online Sales Platform\",\"description\":\"Sebagai bagian dari transformasi digital ACTiV, Accommerce.id memperluas akses pelanggan terhadap berbagai produk teknologi, perangkat keras, serta aksesori profesional melalui platform online yang terstruktur dan terpercaya.<br><br>Platform ini menjadi perpanjangan resmi layanan penjualan ACTiV untuk mendukung kebutuhan perusahaan, institusi, dan individu di seluruh Indonesia.\",\"partner_name\":\"Accommerce.id\",\"partner_logo\":\"\\/assets\\/img\\/partners\\/accommerceid.webp\",\"partner_url\":\"https:\\/\\/accommerce.id\",\"partner_description\":\"Accommerce.id merupakan platform resmi penjualan online dari PT Alfa Cipta Teknologi Virtual (ACTiV) yang menghadirkan solusi pembelian hardware dan lisensi software secara profesional, cepat, dan aman.<br><br>Dirancang sebagai marketplace resmi milik ACTiV, Accommerce memberikan kemudahan transaksi dengan sistem checkout instan serta dukungan purna jual bersertifikat.\",\"feature_title\":\"\\ud83d\\ude80 Keunggulan Platform\",\"features\":[{\"title\":\"Official Online Sales Channel\",\"text\":\"Kanal penjualan digital resmi dan terintegrasi dengan sistem ACTiV.\",\"icon\":\"fa-solid fa-shop\"},{\"title\":\"Transaksi Aman\",\"text\":\"Sistem pembayaran terpercaya dengan keamanan data terenkripsi.\",\"icon\":\"fa-solid fa-lock\"},{\"title\":\"Tracking Pesanan\",\"text\":\"Pelanggan dapat memantau status pengiriman secara real-time.\",\"icon\":\"fa-solid fa-truck-fast\"},{\"title\":\"Layanan Pelanggan 24\\/7\",\"text\":\"Dukungan responsif untuk kebutuhan pre-sales dan after-sales.\",\"icon\":\"fa-solid fa-headset\"},{\"title\":\"Ketersediaan Stok Real-time\",\"text\":\"Informasi stok akurat dan transparan.\",\"icon\":\"fa-solid fa-boxes-stacked\"}],\"steps\":[{\"title\":\"Pendaftaran\",\"description\":\"Isi formulir pengajuan kemitraan melalui situs resmi kami.\"},{\"title\":\"Verifikasi\",\"description\":\"Tim kemitraan kami akan meninjau profil bisnis Anda.\"},{\"title\":\"Onboarding\",\"description\":\"Dapatkan akses ke dashboard partner dan resource teknologi.\"}],\"partner_url_rel\":\"noopener noreferrer nofollow\",\"partner_title\":\"\"}', '2026-02-23 07:51:02', '2026-02-23 08:28:25');

